### ISSUE TITLE
Something wrong with the yarn result

### ISSUE THREAD

**Issue by jornare** [appleboy/npm-vs-yarn#11]
Nice script, but isn't it something fundamentally wrong with the yarn timings?
1ms without any cache is simply not possible.

 -|npm install | npm ci | yarn
-- | -- | -- | --
install without cache (without node_modules) | 3m | 3m | **1ms**
install with cache (without node_modules) | 1m | 18s | 30s
install with cache (with node_modules) | 54s | 21s | 2s
install without internet (with node_modules) | - | - | 2s

**Comment by enkaypeter** [comment]
Hi, it appears to be a typo. From the [testing without cache](https://github.com/appleboy/npm-vs-yarn#testing-without-cache) section, it was stated to be `1m1.261s`. We'll make sure to update the results table right away. Thanks for pointing that out.

**Comment by ThomasGHenry** [comment]
readme still shows ms

**Comment by enkaypeter** [comment]
Yeah...this [commit](https://github.com/enkaypeter/npm-vs-yarn/commit/d7763def0469bfcb87ee5fc215755c0526041e4d) is supposed to fix that. Don't why it hasn't been merged yet
