### ISSUE TITLE
Yarn is already installed in docker node official images

### ISSUE THREAD

**Issue by abumalick** [appleboy/npm-vs-yarn#4]
https://github.com/nodejs/docker-node/blob/47ab48afeb8d17442ee06a476d1b4e8391bc22d4/7.7/Dockerfile

If you want to remove it.

**Comment by appleboy** [comment]
Yes, I know that. I will remove the Yarn and update readme.

**Comment by appleboy** [comment]
fixed in https://github.com/appleboy/npm-vs-yarn/commit/4a97e51d5cf9d89b99d834f38e7bf0076d27fcbd
