### ISSUE TITLE
any update comparison for 2018?

### ISSUE THREAD

**Issue by shiroamada** [appleboy/npm-vs-yarn#5]
any update comparison performance npm vs yarn for 2018?

**Comment by henrik242** [comment]
@appleboy Yeah, an update would be cool

**Comment by appleboy** [comment]
I will take it.

**Comment by henrik242** [comment]
Cool. There is also the new `npm ci` command to consider.

**Comment by appleboy** [comment]
install from npm install with package-lock.json without cache

> real	1m1.009s
> user	0m51.405s
> sys	0m20.663s

install from npm ci with package-lock.json without cache

> real	1m0.268s
> user	0m23.193s
> sys	0m13.480s

install from yarn with yarn.lock without cache

> real	0m46.044s
> user	0m42.042s
> sys	0m29.464s

----------

install from npm install with package-lock.json with cache

> real	0m58.567s
> user	0m40.420s
> sys	0m17.439s

install from npm ci with package-lock.json with cache

> real	0m43.004s
> user	0m21.274s
> sys	0m6.197s

install from yarn with yarn.lock with cache

> real	0m36.384s
> user	0m29.147s
> sys	0m19.763s

**Comment by appleboy** [comment]
Yarn is so faster than npm. We can move package manager from Npm to Yarn for JavaScript now.

|                                              | npm install   | npm ci  | yarn | 
|----------------------------------------------|---------------|---------|------|
| install without cache (without node_modules) | 61s           | 60s     | 46s|
| install with cache (without node_modules)    | 58s           | 43s     | 36s|
| install with cache (with node_modules)       | 10s           | 46s     | `2s`|

**Comment by whoan** [comment]
I think a new test with npm 6 would be needed. See [this blog post](https://mixmax.com/blog/to-yarn-and-back-again-npm) to have an idea of what npm 6 can offer (better performance included).

**Comment by blindbox** [comment]
EDIT: For future readers, these benchmarks are no longer valid. It is only true at the time of writing. Further tests matches the new conclusion that this repo has in the README.md .

Here's my rough benchmark. ~~I only ran it once, so I'm pretty sure that `yarn install without yarn.lock` is not accurate.~~ This is on a private repo.


Round 1.
```
# yarn install without yarn.lock

real    3m18.264s
user    0m0.015s
sys     0m0.060s


# yarn install with yarn.lock

real    1m59.023s
user    0m0.045s
sys     0m0.031s


# npm install without package-lock.json
real    1m42.511s
user    0m0.000s
sys     0m0.077s

# npm install with package-lock.json
real    1m14.273s
user    0m0.015s
sys     0m0.075s
```

Round 2.
```

# yarn install without yarn.lock

real	3m1.640s
user	0m0.030s
sys	0m0.060s


# yarn install with yarn.lock

real	1m55.466s
user	0m0.045s
sys	0m0.045s


# npm install without package-lock.json
real	1m42.369s
user	0m0.015s
sys	0m0.076s

# npm install with package-lock.json
real	1m13.404s
user	0m0.015s
sys	0m0.030s


```

Setup:
```
Windows 10 with windows defender and indexing disabled.

node v10.4.1

npm 6.1.0

yarn 1.7.0
```

The script used:
```bash

## bench.sh
rm -rf node_modules
rm -rf yarn.lock
rm -rf package-lock.json
echo "Fresh yarn install..."
time yarn
rm -rf node_modules
echo "yarn.lock install..."
time yarn
rm -rf node_modules
rm -rf yarn.lock
echo "Fresh npm install..."
time npm install
rm -rf node_modules
echo "package-lock.json install..."
time npm install
```
Ran it using `$ (bash bench.sh) > bench.log 2>&1`.


For adding packages:

```
# yarn add victory

real    0m26.442s
user    0m0.000s
sys    0m0.075s

# add victory to package.json, then yarn install

real    0m17.271s
user    0m0.045s
sys    0m0.015s

# npm install --save victory

real    0m25.147s
user    0m0.030s
sys    0m0.030s

# add victory to package.json, then npm install

real    0m19.614s
user    0m0.000s
```

```bash
# bench-add-package.sh
cp package-original.json package.json
rm -rf node_modules
rm -rf yarn.lock
rm -rf package-lock.json
echo "Fresh yarn install..."
yarn
echo "Add package using yarn add"
time yarn add victory

cp package-original.json package.json
rm -rf node_modules
rm -rf yarn.lock
rm -rf package-lock.json
echo "Fresh yarn install..."
yarn
echo "Add package by updating package-add-json.json"
cp package-add-package.json package.json
time yarn add victory


cp package-original.json package.json
rm -rf node_modules
rm -rf yarn.lock
rm -rf package-lock.json
echo "Fresh npm install..."
npm install
echo "Add package using npm install --save"
time npm install --save victory


cp package-original.json package.json
rm -rf node_modules
rm -rf yarn.lock
rm -rf package-lock.json
echo "Fresh npm install..."
npm install
echo "Add package by updating packaage.json"
cp package-add-package.json package.json
time npm install
```
