### ISSUE TITLE
Re-run with npm@6

### ISSUE THREAD

**Issue by borekb** [appleboy/npm-vs-yarn#9]
Would be interested to see if v6 of npm made any progress here. Also, Yarn is now 1.6.0.

**Comment by levinit** [comment]
@borekb still slow .npm 6.0.1

**Comment by blindbox** [comment]
I've posted my result in #5

**Comment by borekb** [comment]
@blindbox Interesting, so you found npm actually quicker than Yarn.

**Comment by blindbox** [comment]
Yep. I've added the results for `npm install --save` and friends too.

**Comment by slavaguzenko-vicinity** [comment]
Great package - easy to re-run the tests when feeling so.
The results as of today using the latest yarn and npm:

| package manager | time | notes |
|---|---|---|
| YARN v1.9.4 - no cache | 3m28.971s | no built-in audit yet |
| YARN v1.9.4 - with cache | 0m53.248s | no built-in audit yet |
| NPM v6.3.0 - no cache | 3m59.009s | reports vulnerabilities and allows to fix them |
| NPM v6.3.0 - with cache | 0m39.856s | reports vulnerabilities and allows to fix them |

With cache, npm is 25% faster now.

**Comment by appleboy** [comment]
fixed by #10
